{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrixtests
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/matrixTests_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/matrixTests/matrixTests_{{ version }}.tar.gz
  sha256: 0f21dcdf87fc6171423d7b5a0bd3aeec570e954de4aac2f2e14cc800cf8b4188

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrixstats
  run:
    - r-base
    - r-matrixstats

test:
  commands:
    - $R -e "library('matrixTests')"           # [not win]
    - "\"%R%\" -e \"library('matrixTests')\""  # [win]

about:
  home: https://github.com/KKPMW/matrixTests
  license: GPL-2
  summary: "Functions to perform fast statistical hypothesis tests on rows/columns of matrices. The main goals are: 1) speed via vectorization, 2) output that is detailed and easy to use, 3) compatibility with tests implemented in R (like those available in the 'stats' package)."
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: matrixTests
# Title: Fast Statistical Hypothesis Tests on Rows and Columns of Matrices
# Version: 0.1.6
# Authors@R: person("Karolis", "Koncevicius", email = "karolis.koncevicius@gmail.com", role = c("aut", "cre"))
# Maintainer: Karolis Koncevicius <karolis.koncevicius@gmail.com>
# Description: Functions to perform fast statistical hypothesis tests on rows/columns of matrices. The main goals are: 1) speed via vectorization, 2) output that is detailed and easy to use, 3) compatibility with tests implemented in R (like those available in the 'stats' package).
# Depends: R (>= 3.2.2)
# Imports: matrixStats
# Suggests: testthat, moments, car
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/KKPMW/matrixTests
# BugReports: https://github.com/KKPMW/matrixTests/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-19 17:22:13 UTC; karolis
# Author: Karolis Koncevicius [aut, cre]
# Repository: CRAN
# Date/Publication: 2019-09-19 18:00:02 UTC
