travis:
  secure:
    BINSTAR_TOKEN: SmGBJnV/PD0/VVSOz5hk18rJYnSNSckvCZ0DqfyCWh6Zg/nNO+kQSILAo1VTxjcFjp2HP2Az8itHIYWTfckfqzJGwiSQkUkBLnRA1krv75cAfoeC+TJrTxQN+coC0/2c2sO1nA4W45NZhH7QW5uxrHpJd4pBgR6cAJXxwXRcqHr2tCwTcDwLeM9A59UbYiX88M3fsr9CJuGGxsoYcRSaZGQ5+KHjQCzXC91YiXwAdCyNKYVLeG7FLt/YDTJuHoSnvuzL/38pxJIVsvBKuWWTYLcgXKN7BLgVpaCHmUMMjV5YGCOjIU1l0CI2SS1UuMJBWdes3hcXxDvT7K++4eJ/g/nXfWbQk5L4aTFC8bOHNAb8UMDlWLD/3sjce9pkXAx/HefJcIXq52VsoTu2vav95+e3xpGbUQ0ierrP1a1+nxSRE+xXFk2wwxHhKAJJqfKJpqOPTL6U8ArktXvY891wFlnMBaHOYHewa7K3HX2kB0hr06XxM+KLD6B9c8I6kkK6QENM+CgG8oDHF3Yi1N+Cl/qhk5iYuFyGExUKeipJhLrA3F9qNlzjll7UZmgem0XICksZIokLPNG7ZZ5j/IhpHYG102I8TwqhvIVN+87zTOhbqkjF84jabIUpx3tNCQyeGTDfV0r7R/oByXuANOz5UbCz/cEmtV5Pw3+HVp7QIAY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
