appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: YevS0GnBO+8lNny1id55p4MoA+gJwd8wV6XCjfRNtnw6A5Ld1dFgDqZgyheKfhmhKHSTNoXy1A1DThY90taCKjffjD+/jEWBsndJdlYggLJOt00mKKOqtDBBpHUxnCJ7/OvaRkclc0zIPVsmzEr2qYjbOE0D54jBcZ2D7tlu5UTZm8HGaQhVClMCy/KqrSWYcinzB4EuQV13k2HvZHFJsNN8Nf2BBbpmN0KhI4HcPUB40sLEXFcfh1wbRUniAVYWSd6jAeQW79/Do5FGcBs496yK9t9ZQWre4cPTtwb0tmgn4YUWUeS4NHlp4b9I+qGsu6Irl5QMm27pz2+OdUsdSgVlFkBWaaQ8NvjGeaB4ifHZ3eRo+yr36x6Y7fyj92h2Z25fKltBrD0BvELs9YkWoTKrBdObbOzfAI04fD7DU6K8Sb5WEsfuQ6CwFMQVcl6J6Ug0CgZBYdbQgbExMqa81E37Sc9uxfTFtwzoBQsUbaIbvLMDSvlGlgGFqcNwZd4gHvEUsZigcEyxlb9VuKSElVHTFMVNzj/NCqrZMLDkcN7QeJ22IFJo0a8RtO0dJxrKKf1hWMUTLELoPokWY/8JkoJi0v9Cj+68633Fd9kiRthevVHisJSkMWdo4pbLs4Jxlgd++lOpYMXWgCBqs27EcEz3Xj7rqEMv98iz7BAAjDk=
conda_forge_output_validation: true
